"""Data structures shared by the GuardianPixel vision modules."""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np


@dataclass(frozen=True, slots=True)
class ImageInfo:
    """Basic information about a validated cover image."""

    width: int
    height: int
    channels: int
    original_format: str
    original_mode: str

    @property
    def total_pixels(self) -> int:
        return self.width * self.height


@dataclass(slots=True)
class FeatureMaps:
    """Feature maps generated by the vision pipeline."""

    hed_map: np.ndarray
    entropy_map: np.ndarray
    variance_map: np.ndarray
    fused_heatmap: np.ndarray


@dataclass(slots=True)
class BlockMapResult:
    """Result of converting a heatmap to a binary block map."""

    block_size: int
    block_rows: int
    block_columns: int
    selected_blocks: np.ndarray
    selected_block_count: int
    available_position_count: int
    raw_map_bytes: int
    encoded_map_bytes: int
    encoding_type: str


@dataclass(slots=True)
class VisionAnalysisResult:
    """Complete result returned by the Member 1 vision service."""

    image_info: ImageInfo
    feature_maps: FeatureMaps
    block_map: BlockMapResult
    timings: dict[str, float] = field(default_factory=dict)
    config_used: dict = field(default_factory=dict)