import React from 'react';
import { Sparkles } from 'lucide-react';

interface SimulatedBadgeProps {
  label?: string;
  size?: 'sm' | 'md';
  className?: string;
}

export const SimulatedBadge: React.FC<SimulatedBadgeProps> = ({
  label = 'Simulated',
  size = 'sm',
  className = '',
}) => {
  const sizeClasses = size === 'sm' ? 'text-[10px] px-1.5 py-0.5' : 'text-xs px-2 py-0.5';

  return (
    <span
      className={`inline-flex items-center gap-1 font-medium tracking-wide rounded border border-amber-500/30 bg-amber-500/10 text-amber-300 ${sizeClasses} ${className}`}
      title="This value is generated by the client-side mock service until a full backend is connected."
    >
      <Sparkles className={size === 'sm' ? 'w-2.5 h-2.5' : 'w-3 h-3'} />
      {label}
    </span>
  );
};
